const emojiByUnitId: Readonly<Record<string, string>> = {
  airplane: "🛫",
  airport: "🏗️",
  ambulance: "🚑",
  bank: "🏦",
  bigTruck: "🚛",
  bluesMusician: "👨🏿‍🎤",
  capital: "🏰",
  church: "⛪",
  college: "🏫",
  constructionWorker: "👷‍♀️",
  doctor: "👩🏽‍⚕️",
  dragon: "🐉",
  engineer: "👨‍💼",
  factory: "🏭",
  helicopter: "🚁",
  house: "🏠",
  lab: "⚛️",
  leader: "🤴",
  lion: "🐅",
  michaelJackson: "🕴️",
  missile: "🚀",
  money: "💰",
  none: "",
  nuke: "💣",
  office: "🏢",
  pilot: "👩🏾‍✈️",
  port: "🌉",
  priest: "🧙",
  scientist: "👨🏻‍🔬",
  soldier: "💂",
  studentAthlete: "👩‍🎓",
  sub: "⛴",
  truck: "🚙",
  worker: "👨‍🏭",
  zoo: "🥅",
  zookeeper: "👩🏽‍🌾",
  zuckerbird: "👩🏼‍💻",
};

export const getEmojiForUnit = (unitId: string): string => emojiByUnitId[unitId] ?? "◉";

export const getEmojiForAsset = (assetId: string): string =>
  getEmojiForUnit(assetId.startsWith("unit:") ? assetId.slice("unit:".length) : assetId);
